---
- name: Secure SSH Configuration
  hosts: all
  become: yes
  vars:
    ssh_config_file: /etc/ssh/sshd_config

  tasks:
    - name: Backup existing SSH configuration
      copy:
        src: "{{ ssh_config_file }}"
        dest: "{{ ssh_config_file }}.bak"
        owner: root
        group: root
        mode: '0600'
        remote_src: yes

    - name: Ensure SSH configuration is secure
      blockinfile:
        path: "{{ ssh_config_file }}"
        block: |
          # Secure SSH configuration
          Protocol 2
          PermitRootLogin no
          PasswordAuthentication yes
          PubkeyAuthentication no
          PermitEmptyPasswords no
          ChallengeResponseAuthentication no
          UsePAM yes
          AllowTcpForwarding no
          X11Forwarding no
          MaxAuthTries 3
          ClientAliveInterval 300
          ClientAliveCountMax 2
          PermitUserEnvironment no
          LogLevel VERBOSE
          
    - name: Test SSH configuration
      command: sshd -t
      ignore_errors: yes
      register: sshd_test

    - name: Fail if SSH configuration is invalid
      fail:
        msg: "Invalid SSH configuration detected. Check the configuration and try again."
      when: sshd_test.rc != 0

    - name: Ensure the SSH service is enabled and started
      service:
        name: sshd
        enabled: yes
        state: restarted
      when: sshd_test.rc == 0
