---
- name: Secure SSH Configuration
  hosts: all
  become: yes
  vars:
    ssh_config_file: /etc/ssh/sshd_config

  tasks:
    - name: Backup existing SSH configuration
      copy:
        src: "{{ ssh_config_file }}"
        dest: "{{ ssh_config_file }}.bak"
        owner: root
        group: root
        mode: '0600'

    - name: Ensure SSH configuration is secure
      blockinfile:
        path: "{{ ssh_config_file }}"
        block: |
          # Secure SSH configuration
          Protocol 2
          PermitRootLogin no
          PasswordAuthentication yes
          PubkeyAuthentication yes
          PermitEmptyPasswords no
          ChallengeResponseAuthentication no
          UsePAM yes
          AllowTcpForwarding no
          X11Forwarding no
          MaxAuthTries 3
          ClientAliveInterval 300
          ClientAliveCountMax 2
          PermitUserEnvironment no
          LogLevel VERBOSE
          Ciphers aes256-ctr,aes192-ctr,aes128-ctr
          MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160
          KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org
          AllowGroups sshusers

    - name: Ensure the SSH service is enabled and started
      service:
        name: sshd
        enabled: yes
        state: restarted
